/*
 * Orders API
 * Simple API to manage businesses and orders
 *
 * OpenAPI spec version: 1.0.1
 * Contact: sergio.adonis@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OrdersApi);
  }
}(this, function(expect, OrdersApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Business', function() {
      beforeEach(function() {
        instance = new OrdersApi.Business();
      });

      it('should create an instance of Business', function() {
        // TODO: update the code to test Business
        expect(instance).to.be.a(OrdersApi.Business);
      });

      it('should have the property businessId (base name: "businessId")', function() {
        // TODO: update the code to test the property businessId
        expect(instance).to.have.property('businessId');
        // expect(instance.businessId).to.be(expectedValueLiteral);
      });

      it('should have the property businessProps (base name: "businessProps")', function() {
        // TODO: update the code to test the property businessProps
        expect(instance).to.have.property('businessProps');
        // expect(instance.businessProps).to.be(expectedValueLiteral);
      });

    });
  });

}));
