/*
 * Orders API
 * Simple API to manage businesses and orders
 *
 * OpenAPI spec version: 1.0.1
 * Contact: sergio.adonis@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BusinessProps'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BusinessProps'));
  } else {
    // Browser globals (root is window)
    if (!root.OrdersApi) {
      root.OrdersApi = {};
    }
    root.OrdersApi.Business = factory(root.OrdersApi.ApiClient, root.OrdersApi.BusinessProps);
  }
}(this, function(ApiClient, BusinessProps) {
  'use strict';

  /**
   * The Business model module.
   * @module model/Business
   * @version 1.0.1
   */

  /**
   * Constructs a new <code>Business</code>.
   * @alias module:model/Business
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>Business</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Business} obj Optional instance to populate.
   * @return {module:model/Business} The populated <code>Business</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('props'))
        obj.props = BusinessProps.constructFromObject(data['props']);
    }
    return obj;
  }

  /**
   * @member {String} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {module:model/BusinessProps} props
   */
  exports.prototype.props = undefined;

  return exports;

}));
