/*
 * Orders API
 * Simple API to manage businesses and orders
 *
 * OpenAPI spec version: 1.0.1
 * Contact: sergio.adonis@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient';

/**
 * The Business model module.
 * @module model/Business
 * @version 1.0.1
 */
export class Business {
  /**
   * Constructs a new <code>Business</code>.
   * @alias module:model/Business
   * @class
   * @param name {String} 
   */
  constructor(name) {
    this.name = name;
  }

  /**
   * Constructs a <code>Business</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Business} obj Optional instance to populate.
   * @return {module:model/Business} The populated <code>Business</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Business();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('category'))
        obj.category = ApiClient.convertToType(data['category'], 'String');
      if (data.hasOwnProperty('tags'))
        obj.tags = ApiClient.convertToType(data['tags'], ['String']);
      if (data.hasOwnProperty('photoUrl'))
        obj.photoUrl = ApiClient.convertToType(data['photoUrl'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
Business.prototype.id = undefined;

/**
 * @member {String} name
 */
Business.prototype.name = undefined;

/**
 * @member {String} description
 */
Business.prototype.description = undefined;

/**
 * Business category
 * @member {String} category
 */
Business.prototype.category = undefined;

/**
 * labels or tags
 * @member {Array.<String>} tags
 */
Business.prototype.tags = undefined;

/**
 * @member {String} photoUrl
 */
Business.prototype.photoUrl = undefined;

/**
 * Internal business object type
 * @member {String} type
 */
Business.prototype.type = undefined;


