/*
 * Orders API
 * Simple API to manage businesses and orders
 *
 * OpenAPI spec version: 1.0.1
 * Contact: sergio.adonis@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Business', 'model/BusinessBusinessProps', 'model/Error', 'api/BusinessApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/Business'), require('./model/BusinessBusinessProps'), require('./model/Error'), require('./api/BusinessApi'));
  }
}(function(ApiClient, Business, BusinessBusinessProps, Error, BusinessApi) {
  'use strict';

  /**
   * Simple_API_to_manage_businesses_and_orders.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var OrdersApi = require('index'); // See note below*.
   * var xxxSvc = new OrdersApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new OrdersApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new OrdersApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new OrdersApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.0.1
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The Business model constructor.
     * @property {module:model/Business}
     */
    Business: Business,
    /**
     * The BusinessBusinessProps model constructor.
     * @property {module:model/BusinessBusinessProps}
     */
    BusinessBusinessProps: BusinessBusinessProps,
    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error: Error,
    /**
     * The BusinessApi service constructor.
     * @property {module:api/BusinessApi}
     */
    BusinessApi: BusinessApi
  };

  return exports;
}));
