/*
 * Orders API
 * Simple API to manage businesses and orders
 *
 * OpenAPI spec version: 1.0.1
 * Contact: sergio.adonis@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OrdersApi);
  }
}(this, function(expect, OrdersApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OrdersApi.BusinessApi();
  });

  describe('(package)', function() {
    describe('BusinessApi', function() {
      describe('createOneBusiness', function() {
        it('should call createOneBusiness successfully', function(done) {
          // TODO: uncomment, update parameter values for createOneBusiness call and complete the assertions
          /*
          var businessProps = new OrdersApi.Props();

          instance.createOneBusiness(businessProps, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(OrdersApi.Business);
            expect(data.id).to.be.a('string');
            expect(data.id).to.be("12ea34-651d76c-87bd-85b6f9");
            expect(data.props).to.be.a(OrdersApi.BusinessProps);
                  expect(data.props.name).to.be.a('string');
              expect(data.props.name).to.be("El Zócalo");
              expect(data.props.description).to.be.a('string');
              expect(data.props.description).to.be("Restaurante de comida mexicana, tequila, karaoke y mucho más!");
              expect(data.props.category).to.be.a('string');
              expect(data.props.category).to.be("Mexican restaurant");
              {
                let dataCtr = data.props.tags;
                expect(dataCtr).to.be.an(Array);
                expect(dataCtr).to.not.be.empty();
                for (let p in dataCtr) {
                  let data = dataCtr[p];
                  expect(data).to.be.a('string');
                  expect(data).to.be("");
                }
              }
              expect(data.props.photoUrl).to.be.a('string');
              expect(data.props.photoUrl).to.be("https://user-contents.domain.example.com/12ea34-651d76c-87bd-85b6f9");
              expect(data.props.type).to.be.a('string');
              expect(data.props.type).to.be("RSTRNT");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteOneBusiness', function() {
        it('should call deleteOneBusiness successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteOneBusiness call
          /*
          var businessId = "businessId_example";

          instance.deleteOneBusiness(businessId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getBusinessesList', function() {
        it('should call getBusinessesList successfully', function(done) {
          // TODO: uncomment getBusinessesList call and complete the assertions
          /*

          instance.getBusinessesList(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(OrdersApi.Business);
              expect(data.id).to.be.a('string');
              expect(data.id).to.be("12ea34-651d76c-87bd-85b6f9");
              expect(data.props).to.be.a(OrdersApi.BusinessProps);
                    expect(data.props.name).to.be.a('string');
                expect(data.props.name).to.be("El Zócalo");
                expect(data.props.description).to.be.a('string');
                expect(data.props.description).to.be("Restaurante de comida mexicana, tequila, karaoke y mucho más!");
                expect(data.props.category).to.be.a('string');
                expect(data.props.category).to.be("Mexican restaurant");
                {
                  let dataCtr = data.props.tags;
                  expect(dataCtr).to.be.an(Array);
                  expect(dataCtr).to.not.be.empty();
                  for (let p in dataCtr) {
                    let data = dataCtr[p];
                    expect(data).to.be.a('string');
                    expect(data).to.be("");
                  }
                }
                expect(data.props.photoUrl).to.be.a('string');
                expect(data.props.photoUrl).to.be("https://user-contents.domain.example.com/12ea34-651d76c-87bd-85b6f9");
                expect(data.props.type).to.be.a('string');
                expect(data.props.type).to.be("RSTRNT");
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getOneBusiness', function() {
        it('should call getOneBusiness successfully', function(done) {
          // TODO: uncomment, update parameter values for getOneBusiness call and complete the assertions
          /*
          var businessId = "businessId_example";

          instance.getOneBusiness(businessId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(OrdersApi.Business);
            expect(data.id).to.be.a('string');
            expect(data.id).to.be("12ea34-651d76c-87bd-85b6f9");
            expect(data.props).to.be.a(OrdersApi.BusinessProps);
                  expect(data.props.name).to.be.a('string');
              expect(data.props.name).to.be("El Zócalo");
              expect(data.props.description).to.be.a('string');
              expect(data.props.description).to.be("Restaurante de comida mexicana, tequila, karaoke y mucho más!");
              expect(data.props.category).to.be.a('string');
              expect(data.props.category).to.be("Mexican restaurant");
              {
                let dataCtr = data.props.tags;
                expect(dataCtr).to.be.an(Array);
                expect(dataCtr).to.not.be.empty();
                for (let p in dataCtr) {
                  let data = dataCtr[p];
                  expect(data).to.be.a('string');
                  expect(data).to.be("");
                }
              }
              expect(data.props.photoUrl).to.be.a('string');
              expect(data.props.photoUrl).to.be("https://user-contents.domain.example.com/12ea34-651d76c-87bd-85b6f9");
              expect(data.props.type).to.be.a('string');
              expect(data.props.type).to.be("RSTRNT");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('updateOneBusiness', function() {
        it('should call updateOneBusiness successfully', function(done) {
          // TODO: uncomment, update parameter values for updateOneBusiness call and complete the assertions
          /*
          var businessId = "businessId_example";
          var businessProps = new OrdersApi.Props();

          instance.updateOneBusiness(businessId, businessProps, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(OrdersApi.Business);
            expect(data.id).to.be.a('string');
            expect(data.id).to.be("12ea34-651d76c-87bd-85b6f9");
            expect(data.props).to.be.a(OrdersApi.BusinessProps);
                  expect(data.props.name).to.be.a('string');
              expect(data.props.name).to.be("El Zócalo");
              expect(data.props.description).to.be.a('string');
              expect(data.props.description).to.be("Restaurante de comida mexicana, tequila, karaoke y mucho más!");
              expect(data.props.category).to.be.a('string');
              expect(data.props.category).to.be("Mexican restaurant");
              {
                let dataCtr = data.props.tags;
                expect(dataCtr).to.be.an(Array);
                expect(dataCtr).to.not.be.empty();
                for (let p in dataCtr) {
                  let data = dataCtr[p];
                  expect(data).to.be.a('string');
                  expect(data).to.be("");
                }
              }
              expect(data.props.photoUrl).to.be.a('string');
              expect(data.props.photoUrl).to.be("https://user-contents.domain.example.com/12ea34-651d76c-87bd-85b6f9");
              expect(data.props.type).to.be.a('string');
              expect(data.props.type).to.be("RSTRNT");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
