/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.10).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Business;
import io.swagger.model.Error;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-12-06T19:20:21.831Z")

@Api(value = "businesscategory", description = "the businesscategory API")
public interface BusinesscategoryApi {

    @ApiOperation(value = "Create business", nickname = "createBusiness", notes = "", response = Business.class, tags={ "Business", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "ok", response = Business.class),
        @ApiResponse(code = 200, message = "error", response = Error.class, responseContainer = "List") })
    @RequestMapping(value = "/businesscategory/",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Business> createBusiness(@ApiParam(value = "" ,required=true )  @Valid @RequestBody Business bussines);


    @ApiOperation(value = "Get businesses", nickname = "getBusinesses", notes = "", response = Business.class, responseContainer = "List", tags={ "Business", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "ok", response = Business.class, responseContainer = "List"),
        @ApiResponse(code = 200, message = "error", response = Error.class, responseContainer = "List") })
    @RequestMapping(value = "/businesscategory/",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<List<Business>> getBusinesses(@ApiParam(value = "Limit of items in an array to return", defaultValue = "100") @Valid @RequestParam(value = "limit", required = false, defaultValue="100") Integer limit,@ApiParam(value = "Offset to skip in an array to return", defaultValue = "0") @Valid @RequestParam(value = "offset", required = false, defaultValue="0") Integer offset,@ApiParam(value = "") @Valid @RequestParam(value = "category", required = false) String category);

}
