/*
 * Restaurant Orders
 *
 * Simple API to manage restaurant orders
 *
 * OpenAPI spec version: v1
 * Contact: sergio.adonis@outlook.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;

using Microsoft.AspNetCore.Authorization;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class CategoryApiController : ControllerBase
    { 
        /// <summary>
        /// 
        /// </summary>
        /// <param name="body"></param>
        /// <response code="0">Default response</response>
        [HttpPost]
        [Route("/sergioadonis/restaurant-orders-api/v1/categories")]
        [ValidateModelState]
        [SwaggerOperation("AddCategory")]
        [SwaggerResponse(statusCode: 0, type: typeof(InlineResponseDefault1), description: "Default response")]
        public virtual IActionResult AddCategory([FromBody]Category body)
        { 
            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0, default(InlineResponseDefault1));
            string exampleJson = null;
            exampleJson = "{\n  \"objectId\" : 123\n}";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<InlineResponseDefault1>(exampleJson)
                        : default(InlineResponseDefault1);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <response code="0">Default response</response>
        [HttpDelete]
        [Route("/sergioadonis/restaurant-orders-api/v1/categories/{id}")]
        [ValidateModelState]
        [SwaggerOperation("DeleteCategory")]
        [SwaggerResponse(statusCode: 0, type: typeof(InlineResponseDefault1), description: "Default response")]
        public virtual IActionResult DeleteCategory([FromRoute][Required]Id id)
        { 
            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0, default(InlineResponseDefault1));
            string exampleJson = null;
            exampleJson = "{\n  \"objectId\" : 123\n}";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<InlineResponseDefault1>(exampleJson)
                        : default(InlineResponseDefault1);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="limit"></param>
        /// <param name="skip"></param>
        /// <response code="0">ok</response>
        [HttpGet]
        [Route("/sergioadonis/restaurant-orders-api/v1/categories")]
        [ValidateModelState]
        [SwaggerOperation("GetCategories")]
        [SwaggerResponse(statusCode: 0, type: typeof(InlineResponseDefault), description: "ok")]
        public virtual IActionResult GetCategories([FromQuery]int? limit, [FromQuery]int? skip)
        { 
            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0, default(InlineResponseDefault));
            string exampleJson = null;
            exampleJson = "{\n  \"data\" : [ {\n    \"photoUrl\" : \"https://user-contents.domain.example.com/12ea34-651d76c-87bd-85b6f9\",\n    \"name\" : \"Name of object\",\n    \"description\" : \"This is a description for this object, could be Markdown sintax.\",\n    \"id\" : 123\n  }, {\n    \"photoUrl\" : \"https://user-contents.domain.example.com/12ea34-651d76c-87bd-85b6f9\",\n    \"name\" : \"Name of object\",\n    \"description\" : \"This is a description for this object, could be Markdown sintax.\",\n    \"id\" : 123\n  } ]\n}";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<InlineResponseDefault>(exampleJson)
                        : default(InlineResponseDefault);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <response code="0">ok</response>
        [HttpGet]
        [Route("/sergioadonis/restaurant-orders-api/v1/categories/{id}")]
        [ValidateModelState]
        [SwaggerOperation("GetCategoryById")]
        [SwaggerResponse(statusCode: 0, type: typeof(InlineResponseDefault2), description: "ok")]
        public virtual IActionResult GetCategoryById([FromRoute][Required]Id id)
        { 
            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0, default(InlineResponseDefault2));
            string exampleJson = null;
            exampleJson = "{\n  \"data\" : {\n    \"category\" : {\n      \"restaurants\" : [ {\n        \"photoUrl\" : \"https://user-contents.domain.example.com/12ea34-651d76c-87bd-85b6f9\",\n        \"name\" : \"Name of object\",\n        \"description\" : \"This is a description for this object, could be Markdown sintax.\",\n        \"id\" : 123\n      }, {\n        \"photoUrl\" : \"https://user-contents.domain.example.com/12ea34-651d76c-87bd-85b6f9\",\n        \"name\" : \"Name of object\",\n        \"description\" : \"This is a description for this object, could be Markdown sintax.\",\n        \"id\" : 123\n      } ]\n    }\n  }\n}";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<InlineResponseDefault2>(exampleJson)
                        : default(InlineResponseDefault2);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="body"></param>
        /// <param name="id"></param>
        /// <response code="0">Default response</response>
        [HttpPut]
        [Route("/sergioadonis/restaurant-orders-api/v1/categories/{id}")]
        [ValidateModelState]
        [SwaggerOperation("UpdateCategory")]
        [SwaggerResponse(statusCode: 0, type: typeof(InlineResponseDefault1), description: "Default response")]
        public virtual IActionResult UpdateCategory([FromBody]Category body, [FromRoute][Required]Id id)
        { 
            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0, default(InlineResponseDefault1));
            string exampleJson = null;
            exampleJson = "{\n  \"objectId\" : 123\n}";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<InlineResponseDefault1>(exampleJson)
                        : default(InlineResponseDefault1);            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
