/**
 * Orders API
 * Simple API to manage businesses and orders
 *
 * OpenAPI spec version: 1.0.1
 * Contact: sergio.adonis@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.BusinessBusinessProps;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Business {
  
  @SerializedName("businessId")
  private String businessId = null;
  @SerializedName("businessProps")
  private BusinessBusinessProps businessProps = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getBusinessId() {
    return businessId;
  }
  public void setBusinessId(String businessId) {
    this.businessId = businessId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BusinessBusinessProps getBusinessProps() {
    return businessProps;
  }
  public void setBusinessProps(BusinessBusinessProps businessProps) {
    this.businessProps = businessProps;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Business business = (Business) o;
    return (this.businessId == null ? business.businessId == null : this.businessId.equals(business.businessId)) &&
        (this.businessProps == null ? business.businessProps == null : this.businessProps.equals(business.businessProps));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.businessId == null ? 0: this.businessId.hashCode());
    result = 31 * result + (this.businessProps == null ? 0: this.businessProps.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Business {\n");
    
    sb.append("  businessId: ").append(businessId).append("\n");
    sb.append("  businessProps: ").append(businessProps).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
